apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    
spec:
  project: argocd-poc-automation
  source:
    path: argo-cd/base
    repoURL: https://github.com/sandeepitachi/argocd-poc-automation.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
